name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: x64
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Poetry Version
        run: |
          poetry -V
      - name: Poetry Install Dependencies
        run: |
          poetry install --no-interaction
      - name: Test with pytest
        run: |
          poetry run python -m pytest -vv
